### PR TITLE
misc fixes

### PR DESCRIPTION
**Pull request by utkarshayachit**
fixes to imports.

these were exposed by ParaView.

### CODE REVIEW

**Comment by utkarshayachit** [comment]
@dhrogers, any ideas why the tests are failing? thanks.

**Comment by EthanS94** [comment]
@utkarshayachit @dhrogers I suspect something changed in Travis recently, because the master branch test (which was successful 3 days ago) is failing with the same error. I'll see if I can find out why.

**Comment by EthanS94** [comment]
The link that hosts the colormap used in that tests had outdated SSL certificate. I updated the certificate and restarted the test.

**Comment by dhrogers** [comment]
Ethan - 

Not sure I understand this. Why would it happen, and how to we keep this working in the future?

If it's going to break in ways we can't control or update automatically, we need to change the test.

Thanks,
David

**Comment by EthanS94** [comment]
@dhrogers At some point in the tests, colormaps are pulled from:
`https://sciviscolor.org/wp-content/uploads/sites/14/2017/09/blue-orange-div.xml`
and
`https://sciviscolor.org/wp-content/uploads/sites/14/2017/09/blue-1.xml`.

To avoid this in the future, I think those could be changed to links controlled by this repo (second colormap would need to be added):
`https://raw.githubusercontent.com/cinemascience/cinemasci/master/testing/gold/cis/file.cis/colormaps/blue-orange-div.xml`
and
`https://raw.githubusercontent.com/cinemascience/cinemasci/master/testing/gold/cis/file.cis/colormaps/blue-1.xml`

**Comment by dhrogers** [comment]
@EthanS94 - that's a good solution. I'm implementing it now.

**Comment by dhrogers** [comment]
@utkarshayachit @EthanS94 This is merged, and I updated the tests to pull data from the repository, instead of the sciviscolor URL.

**Pull request merged**
